[package]
name = "td"
version = "0.1.0"
edition = "2021"

[dependencies]
time = { version = "0.3.19", features = ["formatting", "parsing", "local-offset", "large-dates", "macros"] }

[dev-dependencies]
pretty_assertions = "1"
